openapi: 3.0.0
info:
  version: v1
  title: Legacy API (v1) Account Tag API
  description: ''
servers:
- url: https://app.practicepanther.com
tags:
- name: Tag
paths:
  /api/tag:
    get:
      tags:
      - Tag
      summary: OData end point to get a list of all tags
      operationId: Tag_GetTags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagDTO'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagDTO'
      security:
      - oauth2:
        - full
components:
  schemas:
    TagDTO:
      required:
      - name
      type: object
      properties:
        name:
          type: string
  securitySchemes:
    oauth2:
      type: oauth2
      description: OAuth 2.0 - Authorization Code Grant
      flows:
        authorizationCode:
          authorizationUrl: /OAuth/Authorize
          tokenUrl: /OAuth/Token
          scopes:
            full: Read/Write access to all resources
